# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fzzkill/Projects/refcs/FCS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fzzkill/Projects/refcs/FCS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fzzkill/Projects/refcs/FCS/CMakeFiles /home/fzzkill/Projects/refcs/FCS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fzzkill/Projects/refcs/FCS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FCS.cpp

# Build rule for target.
FCS.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FCS.cpp
.PHONY : FCS.cpp

# fast build rule for target.
FCS.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FCS.cpp.dir/build.make CMakeFiles/FCS.cpp.dir/build
.PHONY : FCS.cpp/fast

Error/_Error/Error.o: Error/_Error/Error.cpp.o
.PHONY : Error/_Error/Error.o

# target to build an object file
Error/_Error/Error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FCS.cpp.dir/build.make CMakeFiles/FCS.cpp.dir/Error/_Error/Error.cpp.o
.PHONY : Error/_Error/Error.cpp.o

Error/_Error/Error.i: Error/_Error/Error.cpp.i
.PHONY : Error/_Error/Error.i

# target to preprocess a source file
Error/_Error/Error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FCS.cpp.dir/build.make CMakeFiles/FCS.cpp.dir/Error/_Error/Error.cpp.i
.PHONY : Error/_Error/Error.cpp.i

Error/_Error/Error.s: Error/_Error/Error.cpp.s
.PHONY : Error/_Error/Error.s

# target to generate assembly for a file
Error/_Error/Error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FCS.cpp.dir/build.make CMakeFiles/FCS.cpp.dir/Error/_Error/Error.cpp.s
.PHONY : Error/_Error/Error.cpp.s

System/System_String.o: System/System_String.cpp.o
.PHONY : System/System_String.o

# target to build an object file
System/System_String.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FCS.cpp.dir/build.make CMakeFiles/FCS.cpp.dir/System/System_String.cpp.o
.PHONY : System/System_String.cpp.o

System/System_String.i: System/System_String.cpp.i
.PHONY : System/System_String.i

# target to preprocess a source file
System/System_String.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FCS.cpp.dir/build.make CMakeFiles/FCS.cpp.dir/System/System_String.cpp.i
.PHONY : System/System_String.cpp.i

System/System_String.s: System/System_String.cpp.s
.PHONY : System/System_String.s

# target to generate assembly for a file
System/System_String.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FCS.cpp.dir/build.make CMakeFiles/FCS.cpp.dir/System/System_String.cpp.s
.PHONY : System/System_String.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FCS.cpp"
	@echo "... Error/_Error/Error.o"
	@echo "... Error/_Error/Error.i"
	@echo "... Error/_Error/Error.s"
	@echo "... System/System_String.o"
	@echo "... System/System_String.i"
	@echo "... System/System_String.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

